# Generated by Django 6.0.1 on 2026-02-03 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(max_length=20)),
                ('manufacturer', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('variant', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('fuel_type', models.CharField(max_length=20)),
                ('registration_year', models.IntegerField()),
                ('registration_valid', models.BooleanField(default=True)),
                ('engine_capacity', models.IntegerField()),
                ('emission_norm', models.CharField(max_length=20)),
                ('chassis_number', models.CharField(max_length=50)),
                ('engine_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DrivingLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=30)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('license_class', models.CharField(max_length=10)),
                ('issuing_authority', models.CharField(max_length=50)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='LicensePlate.owner')),
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='LicensePlate.vehicle'),
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('policy_number', models.CharField(max_length=50)),
                ('policy_type', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='LicensePlate.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_certificate', models.BooleanField(default=False)),
                ('insurance_document', models.BooleanField(default=False)),
                ('pollution_certificate', models.BooleanField(default=False)),
                ('fitness_certificate', models.CharField(choices=[('Valid', 'Valid'), ('Due Soon', 'Due Soon'), ('Expired', 'Expired')], default='Valid', max_length=20)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='LicensePlate.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_date', models.DateField()),
                ('fine_amount', models.IntegerField()),
                ('accident', models.BooleanField(default=False)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LicensePlate.vehicle')),
            ],
        ),
    ]
