# Generated by Django 6.0.1 on 2026-02-03 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LicensePlate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('iso_code', models.CharField(max_length=3, unique=True)),
                ('phone_code', models.CharField(max_length=5)),
                ('driving_side', models.CharField(choices=[('L', 'Left'), ('R', 'Right')], max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='LicensePlate.country'),
            preserve_default=False,
        ),
    ]
