# Generated by Django 6.0.1 on 2026-02-25 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LicensePlate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('iso_code', models.CharField(max_length=3, unique=True)),
                ('phone_code', models.CharField(max_length=5)),
                ('driving_side', models.CharField(choices=[('L', 'Left'), ('R', 'Right')], max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='nationality',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='owner',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='violation',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='violation',
            name='violation_type',
            field=models.CharField(choices=[('speeding', 'Over Speeding'), ('signal', 'Signal Jump'), ('helmet', 'No Helmet')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='owner',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='owner',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='owner',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='owner',
            name='vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LicensePlate.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='LicensePlate.country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='LicensePlate.country'),
        ),
    ]
