# Generated by Django 6.0.1 on 2026-02-03 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LicensePlate', '0002_country_vehicle_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='nationality',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='LicensePlate.country'),
        ),
    ]
