# Generated by Django 6.0.1 on 2026-02-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LicensePlate', '0003_owner_nationality_alter_owner_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='violation',
            name='violation_type',
            field=models.CharField(choices=[('speeding', 'Over Speeding'), ('signal', 'Signal Jump'), ('helmet', 'No Helmet')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
