# Generated by Django 6.0.1 on 2026-02-25 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LicensePlate', '0003_alter_owner_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='user',
        ),
    ]
