# Generated by Django 6.0.1 on 2026-02-26 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LicensePlate', '0004_remove_owner_user'),
        ('LicensePlate', '0004_violation_is_paid_violation_violation_type'),
    ]

    operations = [
    ]
