# Generated by Django 6.0.1 on 2026-02-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='videos/')),
                ('processed_video', models.FileField(blank=True, null=True, upload_to='processed/')),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='csvs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('status', models.CharField(default='Pending', max_length=100)),
            ],
        ),
    ]
