# Generated by Django 6.0.1 on 2026-02-05 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoupload',
            name='processed_video',
        ),
        migrations.RemoveField(
            model_name='videoupload',
            name='status',
        ),
    ]
