# Generated by Django 6.0.1 on 2026-02-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpr', '0002_remove_videoupload_processed_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='processed_video',
            field=models.FileField(blank=True, null=True, upload_to='processed_videos/'),
        ),
    ]
