# Generated by Django 6.0.1 on 2026-02-26 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LicensePlate', '0005_merge_20260225_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=256)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='LicensePlate.owner')),
            ],
        ),
    ]
